//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertPlayer
    {
        public int ExpertPlayerID { get; set; }
        public int ExpertID { get; set; }
        public string ExpertPlayerName { get; set; }
        public Nullable<int> PlayerID { get; set; }
    
        public virtual Expert Expert { get; set; }
    }
}
