//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Rankings = new HashSet<Ranking>();
            this.SkillPlayerStats = new HashSet<SkillPlayerStat>();
        }
    
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string Nickname { get; set; }
        public byte PositionID { get; set; }
        public byte TeamID { get; set; }
        public bool Retired { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<Ranking> Rankings { get; set; }
        public virtual ICollection<SkillPlayerStat> SkillPlayerStats { get; set; }
    }
}
