//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int RankingID { get; set; }
        public int Season { get; set; }
        public int ExpertID { get; set; }
        public int PlayerID { get; set; }
        public int Rank { get; set; }
        public Nullable<int> Tier { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Player Player { get; set; }
    }
}
