//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillPlayerStat
    {
        public int SkillPlayerStatID { get; set; }
        public int PlayerID { get; set; }
        public int Season { get; set; }
        public Nullable<int> RushAtt { get; set; }
        public Nullable<double> RushYds { get; set; }
        public Nullable<int> RushTDs { get; set; }
        public Nullable<int> Receptions { get; set; }
        public Nullable<double> RecYds { get; set; }
        public Nullable<int> RecTDs { get; set; }
        public Nullable<int> PassAtt { get; set; }
        public Nullable<int> PassComp { get; set; }
        public Nullable<double> PassYds { get; set; }
        public Nullable<int> PassTDs { get; set; }
        public Nullable<int> INTs { get; set; }
        public Nullable<int> Fumbles { get; set; }
        public Nullable<int> Conv2Pt { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
