//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Players = new HashSet<Player>();
        }
    
        public byte TeamID { get; set; }
        public string TeamName { get; set; }
        public string Abbreviation { get; set; }
        public string State { get; set; }
        public string FirstName { get; set; }
        public string Conference { get; set; }
        public string Division { get; set; }
    
        public virtual ICollection<Player> Players { get; set; }
    }
}
